apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::353009653875:user/telemetry-admin
      username: telemetry-admin
      groups:
        - system:masters
