apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-api
  labels:
    app: telemetry-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: telemetry-api
  template:
    metadata:
      labels:
        app: telemetry-api
    spec:
      containers:
        - name: telemetry-api
          image: 353009653875.dkr.ecr.eu-central-1.amazonaws.com/telemetry-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://telemetry-db.database.svc.cluster.local:5432/multi_tenant_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "mypassword"
---
apiVersion: v1
kind: Service
metadata:
  name: telemetry-api-service
spec:
  selector:
    app: telemetry-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer